---
title: "Chapter-12-assignment-03"
author: "Ruijuan Li"
date: "11/30/2016"
output: 
  html_document: 
    keep_md: yes
---

# 12E3
```{r}
# y ~ Normal(mui, sigma1)
# mui = a + a_group[i] + bxi
# a_group ~ Normal(0, sigma2)
# c(a,b) ~ Nomral(0,10)
# c(sigma1, sigma2) ~ HalfCauchy(0, 2)
```

# 12E4
```{r}
# y ~ Possion(mui)
# log(mui) <- a+ a_group[i] + blogPi # get this from page 382, but don't understand the log part... 
# a_group ~ Normal(0, sigma)
# c(a,b) ~ Normal(0, 10)
# sigma ~ HalfCauchy(0, 1)
```

# 12E5
```{r}
# y ~ Possion(mui)
# log(mui) <- a+ a_group_i[i] + a_group_ii[ii] + blogPi 
# a_group_i ~ Normal(0, sigma_i)
# a_group_ii ~ Normal(0, sigma_ii)
# c(a,b) ~ Normal(0, 10)
# c(sigma_i, sigmal_ii) ~ HalfCauchy(0, 1)
```

# 12M4 
```{r}
# fit a cross-classified multilevel model to the chimp data 
library(rethinking)
data("chimpanzees")
d <- chimpanzees
head(chimpanzees)

# Two types of clusters 
# prep data 
d$recipient <- NULL
d$block_id <- d$block # name 'block' is reserved by Stan 

# model in the chapter 
m12M4.1 <- map2stan(
  alist(
    pulled_left ~ dbinom(1, p), 
    logit(p) <- a + a_actor[actor] + a_block[block_id] + 
      (bp + bpC*condition)*prosoc_left,
    a_actor[actor] ~ dnorm(0, sigma_actor), 
    a_block[block_id] ~ dnorm(0, sigma_block), 
    a ~ dnorm(0, 10), 
    bp ~ dnorm(0, 10), 
    bpC ~ dnorm(0, 10), 
    sigma_actor ~ dcauchy(0, 1), 
    sigma_block ~ dcauchy(0, 1)
  ), 
  data = d, warmup = 1000, iter = 6000, chains = 4, cores = 3)

# model in here 
m12M4.2 <- map2stan(
  alist(
    pulled_left ~ dbinom(1, p), 
    logit(p) <- a_actor[actor] + a_block[block_id] + 
      (bp + bpC*condition)*prosoc_left,
    a_actor[actor] ~ dnorm(a, sigma_actor), 
    a_block[block_id] ~ dnorm(rho, sigma_block), 
    a ~ dnorm(0, 10), 
    rho ~ dnorm(0, 10),
    bp ~ dnorm(0, 10), 
    bpC ~ dnorm(0, 10), 
    sigma_actor ~ dcauchy(0, 1), 
    sigma_block ~ dcauchy(0, 1)
  ), 
  data = d, warmup = 1000, iter = 6000, chains = 4, cores = 3)

# check the summary result of these two models 
# compare the numher of effective samples 
precis(m12M4.1, depth = 2)
precis(m12M4.2, depth = 2) # bad Rhat & n_eff 
plot(m12M4.1)
plot(m12M4.2) # bad !!! 
par(mfrow=c(1,1))

# get posterior distribution of this new model 
post.m12M4.1 <- extract.samples(m12M4.1)
post.m12M4.2 <- extract.samples(m12M4.2)
  
# compare the posterior distibution with the model in the chapter 
par(mfrow=c(2,1))
dens(post.m12M4.1$sigma_block, xlab="sigma", xlim=c(0,4))
dens(post.m12M4.1$sigma_actor, col=rangi2, lwd=2, add = T)
text(2, 0.85, "actor", col = rangi2)
text(0.75, 2, "block")

dens(post.m12M4.2$sigma_block, xlab="sigma", xlim=c(0,4))
dens(post.m12M4.2$sigma_actor, col=rangi2, lwd=2, add = T)
text(2, 0.85, "actor", col = rangi2)
text(0.75, 2, "block")
par(mfrow=c(1,1))

# explain the differences
# the model here has bad Rhat and very small number of effective samples. Also a narrower posterior distribution of sigma compared to the model created in the chapter, although the peak is about the same. Why???? because the non-zero alpha ...  
```





