---
title: "Chapter-10-assignment"
author: "Ruijuan Li"
date: "September 5, 2016"
output: 
  html_document: 
    keep_md: yes
---

# 10E1
```{r}
# If an event has probability 0.35, what are the log-odds of this event? 
# what is log-odds? "odds are the ratio of the probability an event happens to the probability it does not happen. log-odds is the log of odds" 

p.10E1 <- 0.35 
odds.10E1 <- 0.35/(1-0.35)
log.odds.10E1 <- log(odds.10E1)
log.odds.10E1
```

# 10E2
```{r}
# If an event has log-odds 3.2, what is the probability of this event? 
log.odds.10E2 <- 3.2
odds.10E2 <- exp(3.2)
# since odds.10E2 = p/1-p, and odds.10E2 = 24.53253, so 
p.10E2 = odds.10E2/(odds.10E2+1)
p.10E2
```

# 10E3
```{r}
# Suppose that a coefficient in a logistic regression has value 1.7. What does this imply about the proportional change in odds of the outcome? 
# "The customary measure of relative effect for a logistic model is the PROPORTIONAL CHANGE IN ODDS. You can compute the proportional odds by merely exponentiating the parameter estimate."
exp(1.7)-1 # the odds increase by 447% 
```

# 10M1 
```{r}
# As explained in the chapter, binomial data can be organized in aggregated and disaggregated forms, without any impact on inference. But the likelihood of the data does change when the data are converted between the two formats. Can you explain why? 
# what is aggregated form? what is disaggregated form? based on my understanding, aggregated form is the model prediction with a number of trails, while disaggregated form is from a single trail. 
# what is inference? inference is the model prediction/extract result
# what is likelihood? likelihood is the precis result I think 

# because the likelihood for aggregated form defines the probability of each count out of n trails with distinct combinations, whereas the likelihood for disaggregated form defines the probability of each count out of a single trail.   

```

# 10H1
```{r}
#  Use map to construct a quadratic approximate posterior distribution for the chimpanzee model that includes a unique intercept for each actor, m10.4 (page 299). Compare the quadratic approximation to the posterior distribution produced instead from MCMC. Can you explain both the differences and the similarities between the approximate and the MCMC distributions?  

library(rethinking)
data("chimpanzees")
d <- chimpanzees
d2 <- d
d2$recipient <- NULL


m10.4 <- map2stan(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <- a[actor] + (bp + bpC*condition)*prosoc_left,
    a[actor] ~ dnorm(0, 10),
    bp ~ dnorm(0, 10),
    bpC ~ dnorm(0, 10)
  ), 
  data = d2, chains = 2, iter = 2500, warmup = 500)

m10.4.map <- map(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <- a[actor] + (bp + bpC*condition)*prosoc_left,
    a[actor] ~ dnorm(0, 10),
    bp ~ dnorm(0, 10),
    bpC ~ dnorm(0, 10)
  ), 
  data = d) 

precis(m10.4)
precis(m10.4.map)
# the result is very similar... difference... the way of their calculation is different.. how different??? 
```

# 10H2
```{r}
# Use WAIC to compare the chimpanzee model that includes a unique intercept for each actor, m10.4 (page 299), to the simpler models fit in the same section. 
m10.1 <- map(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <- a, 
    a ~ dnorm(0, 10)
  ), 
  data = d)

m10.2 <- map(
  alist(
    pulled_left ~ dbinom(1, p), 
    logit(p) <- a + bp*prosoc_left, 
    a ~ dnorm(0, 10), 
    bp ~ dnorm(0, 10)
  ), 
  data = d)

m10.3 <- map(
  alist(
    pulled_left ~ dbinom(1, p), 
    logit(p) <- a + (bp + bpC*condition)*prosoc_left,
    a ~ dnorm(0, 10), 
    bp ~ dnorm(0, 10), 
    bpC ~ dnorm(0, 10)
  ), 
  data = d)

m10.3stan <- map2stan(m10.3, data = d2, iter = 1e4, warmup = 1000)

compare(m10.4, m10.3, m10.2, m10.1, m10.3stan)
```







