---
title: "Chapter-07-part1-assignment"
author: "Ruijuan Li"
date: "May 25, 2016"
output: 
  html_document: 
    keep_md: yes
---

# 7E1
```{r}
# For each of the causal relationships below, name a hypothetical third variable that would lead to an interaction effect.

# (1)	Bread dough rises because of yeast. temperature 

# (2)	Education leads to higher income. major 

# (3)	Gasoline makes a car go. a working engine 
```

# 7E2
```{r}
# Which of the following explanations invokes an interaction? 1 

# (1)	Caramelizing onions requires cooking over low heat and making sure the onions do not dry out. 

# (2)	A car will go faster when it has more cylinders or when it has a better fuel injector.

# (3)	Most people acquire their political beliefs from their parents, unless they get them instead from their friends.

# (4)	Intelligent animal species tend to be either highly social or have manipulative appendages (hands, tentacles, etc.). 
```

#7E3
```{r}
# For each of the explanations in 7E2, write a linear model that expresses the stated relationship. 

# 1) onion.taste <- a + bt*temperature + bm*moisture.level.onion + btm*temperature*moisture.level.onion

# onion.taste ~ temperature*moisture.level.onion 
```

#7M1
```{r}
# Recall the tulips example from the chapter. Suppose another set of treatments adjusted the temperature in the greenhouse over two levels: cold and hot. The data in the chapter were collected at the cold temperature. You find none of the plants grown under the hot temperature developed any blooms at all, regardless of the water and shade levels. Can you explain this result in terms of interactions between water, shade, and temperature? 

# Plant growth is dependent upon three factors: water, shade, and temperatures, and the effect of water and shade on plant growth is dependent upon the temperature level in the greenhouse.  
```

#7M2
```{r}
# Can you invent a regression equation that would make the bloom size zero, whenever the temperature is hot? (the concept of dummy & centered variable???)

# bloom.size = shade: cool + water : cool + shade:water:cool 
# no main effect here ... 
```

#7M3
```{r}
# In parts of North America, ravens depend upon wolves for their food. This is because ravens are carnivorous but cannot usually kill or open carcasses of prey. Wolves however can and do kill and tear open animals, and they tolerate ravens co-feeding at their kills. This species relationship is generally described as a “species interaction.” Can you invent a hypothetical set of data on raven population size in which this relationship would manifest as a statistical interaction? Do you think the biological interaction could be linear? Why or why not? 
# How to understand linear interaction? 

```

#7H1 
```{r, include==FALSE}
# Return to the data(tulips) example in the chapter. Now include the bed variable as a predictor in the interaction model. Don't interact bed with the other predictors; just include it as a main effect. Note that bed is categorical. So to use it properly, you will need to either construct dummy variables or rather an index variable, as explained in Chapter 5. 

library(rethinking)
data("tulips")
d <- tulips

# center the predictor
d$shade.c <- d$shade - mean(d$shade)
d$water.c <- d$water - mean(d$water)

# create dummy variable
d$bed.a <- ifelse(d$bed=="a", 1, 0)
d$bed.b <- ifelse(d$bed=="b", 1, 0)
d

# fit the model 
m7H1 <- map(
  alist(
    blooms ~ dnorm(mu, sigma),
    mu <- a + bW*water.c + bS*shade.c + bWS*water.c*shade.c + ba*bed.a + bb*bed.b,
    a ~ dnorm(130, 100),
    bW ~ dnorm(0, 100),
    bS ~ dnorm(0, 100),
    bWS ~ dnorm(0, 100),
    ba ~ dnorm(0, 1),
    bb ~ dnorm(0, 1),
    sigma ~ dunif(0, 100)
  ), 
  data = d,
  start = list(a=mean(d$blooms), bS=0, bS=0, bWS=0, ba=0, bb=0, sigma=sd(d$blooms))
)

```

#7H2
```{r, echo=FALSE}
# Use WAIC to compare the model from 7H1 to a model that omits bed. What do you infer from this comparison? Can you reconcile the WAIC results with the posterior distribution of the bed coefficients? 

# the model that moits bed
m7.9 <- map(
  alist(
    blooms ~ dnorm(mu, sigma),
    mu <- a + bW*water.c + bS*shade.c + bWS*water.c*shade.c,
    a ~ dnorm(130, 100),
    bW ~ dnorm(0, 100),
    bS ~ dnorm(0, 100),
    bWS ~ dnorm(0, 100),
    sigma ~ dunif(0, 100)
  ), 
  data = d,
  method = "Nelder-Mead",
  control = list(maxit=1e4),
  start = list(a=mean(d$blooms), bS=0, bS=0, bWS=0, sigma=sd(d$blooms))
)

WAIC(m7H1)
WAIC(m7.9) 
compare(m7H1, m7.9) # which one is better? hard to say... 

# Can you reconcile the WAIC results with the posterior distribution of the bed coefficients? what does this mean? 

```

#7H3
```{r, echo=FALSE}
data(rugged)
d <- rugged

head(d)
dim(d) #234 countries w/ 51 sets of data 
# make log version of outcome
d$log_gdp <- log(d$rgdppc_2000)

dd <- d[complete.cases(d$rgdppc_2000), ]
dim(dd) # 170 countries 170 52 
dd$country

# The previous model w/ all African countries 
m7.5b <- map(
  alist(
    log_gdp ~ dnorm(mu, sigma),
    mu <- a + bR*rugged + bAR*rugged*cont_africa + bA*cont_africa,
    a ~ dnorm(8, 100),
    bA ~ dnorm(0, 1),
    bR ~ dnorm(0, 1),
    bAR ~ dnorm(0, 1),
    sigma ~ dunif(0, 10)
  ), data = dd)

# drop Seychelles
dd_noSey <- dd[-(dd$country=="Seychelles"),]
dim(dd_noSey) # 169 52 

# (a) drop Seychelles from the data and re-evaluate the hypothesis that the relationship of African economies with ruggedness is different from that on other continents. 

m7H3 <- map(
  alist(
    log_gdp ~ dnorm(mu, sigma),
    mu <- a + bR*rugged + bAR*rugged*cont_africa + bA*cont_africa,
    a ~ dnorm(8, 100),
    bA ~ dnorm(0, 1),
    bR ~ dnorm(0, 1),
    bAR ~ dnorm(0, 1),
    sigma ~ dunif(0, 10)
  ), data = dd_noSey)

# compare the coefficents of these two models 
coeftab(m7.5b, m7H3)
# almost no difference. only sigma is different, dropping Seychelles increases sigma/ increases uncertainty. 

# (b) plot to visualize the relationship in these two models 
# the old model 
rugged.seq <- seq(-1, 8, by = 0.25)

mu.Africa <- link(m7.5b, data = data.frame(cont_africa=1, rugged= rugged.seq))
mu.Africa.mean <- apply(mu.Africa, 2, mean)
mu.Africa.PI <- apply(mu.Africa, 2, PI, prob= 0.97)

mu.NotAfrica <- link(m7.5b, data = data.frame(cont_africa=0, rugged= rugged.seq))
mu.NotAfrica.mean <- apply(mu.NotAfrica, 2, mean)
mu.NotAfrica.PI <- apply(mu.NotAfrica, 2, PI, prob= 0.97)

# plot Afican nations w/ regression, plot using subset of data (Africa/NonAfrica)
d.A1 <- dd[dd$cont_africa==1,]

plot(log(rgdppc_2000) ~ rugged, data=d.A1,
     col=rangi2, ylab="log GDP year 2000",
     xlab="Terrain Ruggedness Index")
mtext("African nations", 3)
lines(rugged.seq, mu.Africa.mean, col=rangi2)
shade(mu.Africa.PI, rugged.seq, col = col.alpha(rangi2, 0.3))

# plot non-Afican nations w/ regression
d.A0 <- dd[dd$cont_africa==0,]

plot(log(rgdppc_2000) ~ rugged, data=d.A0,
     col="black", ylab="log GDP year 2000",
     xlab="Terrain Ruggedness Index")
mtext("Non-African nations", 3)
lines(rugged.seq, mu.NotAfrica.mean, col=rangi2)
shade(mu.NotAfrica.PI, rugged.seq)

# The new model 
rugged.seq <- seq(-1, 8, by = 0.25)

mu.Africa <- link(m7H3, data = data.frame(cont_africa=1, rugged= rugged.seq))
mu.Africa.mean <- apply(mu.Africa, 2, mean)
mu.Africa.PI <- apply(mu.Africa, 2, PI, prob= 0.97)

mu.NotAfrica <- link(m7H3, data = data.frame(cont_africa=0, rugged= rugged.seq))
mu.NotAfrica.mean <- apply(mu.NotAfrica, 2, mean)
mu.NotAfrica.PI <- apply(mu.NotAfrica, 2, PI, prob= 0.97)

# plot Afican nations w/ regression, plot using subset of data (Africa/NonAfrica)
d.A1 <- dd_noSey[dd_noSey$cont_africa==1,]
plot(log(rgdppc_2000) ~ rugged, data=d.A1,
     col=rangi2, ylab="log GDP year 2000",
     xlab="Terrain Ruggedness Index")
mtext("African nations", 3)
lines(rugged.seq, mu.Africa.mean, col=rangi2)
shade(mu.Africa.PI, rugged.seq, col = col.alpha(rangi2, 0.3))

# plot non-Afican nations w/ regression
d.A0 <- dd_noSey[dd_noSey$cont_africa==0,]

plot(log(rgdppc_2000) ~ rugged, data=d.A0,
     col="black", ylab="log GDP year 2000",
     xlab="Terrain Ruggedness Index")
mtext("Non-African nations", 3)
lines(rugged.seq, mu.NotAfrica.mean, col=rangi2)
shade(mu.NotAfrica.PI, rugged.seq)

# it still look like the effect of ruggedness depends upon continent, I didn't see any obvious difference. 

# (c) conduct model comparsion, fit three models to the data w/o Seychelles
m7H3.1 <- map(
  alist(
    log_gdp ~ dnorm(mu, sigma),
    mu <- a + bR*rugged,
    a ~ dnorm(8, 100),
    bR ~ dnorm(0, 1),
    sigma ~ dunif(0, 10)
  ), data = dd_noSey)

m7H3.2 <- map(
  alist(
    log_gdp ~ dnorm(mu, sigma),
    mu <- a + bR*rugged + bA*cont_africa,
    a ~ dnorm(8, 100),
    bA ~ dnorm(0, 1),
    bR ~ dnorm(0, 1),
    sigma ~ dunif(0, 10)
  ), data = dd_noSey)

compare(m7H3, m7H3.1, m7H3.2) # 7H3 looks much better, it is the one that includes interaction effect.

# model averaging 
m7H3.ensemble <- ensemble(m7H3, m7H3.1, data = dd_noSey) # should m7H3.2 be added? 0 weight. 
m7H3.ensemble$link

# didn't get time to do this, but I guess there is no huge difference between these two models, because m7H3 takes over a large weight based on the model comparison result. 

rugged.seq <- seq(-1, 8, by = 0.25)

# mu <- apply(m7H3.ensemble$link, 2, mean)
# mu.PI < apply(m7H3.ensemble$link, 2, PI)
# lines(rugged.seq, mu)
# shade(mu.PI, rugged.seq) # How to calculate mu and PI for African & non-African countries seperately? 

# plot Afican nations w/ regression, plot using subset of data (Africa/NonAfrica)

# plot non-Afican nations w/ regression

```

#7H4
```{r, echo=FALSE}
data(nettle)
d <- nettle
head(nettle)
dim(nettle) # 74 7

d$lang.per.cap <- d$num.lang/d$k.pop
head(d)
dim(d)

# (a) Evaluate the hypothesis that language diversity, as measured by log(lang.per.cap), is positively associated with the average length of the growing season, mean.growing.season. Consider log(area) in your regression(s) as a covariate (not an interaction). Interpret your results.

d$log.lang.per.cap <- log(d$lang.per.cap)
d$log.area <- log(d$area)

mean(d$log.lang.per.cap)
sd(d$log.lang.per.cap)

m7H4.a <- map(
  alist(
    log.lang.per.cap ~ dnorm(mu, sigma),
    mu <- a + bg*mean.growing.season + ba*log.area,
    a ~ dnorm(0, 10),
    bg ~ dnorm(0, 1),
    ba ~ dnorm(0, 1),
    sigma ~ dunif(0, 10)
  ), data = d)
  
precis(m7H4.a)
# based on the coeffecient of mean.growing.season and its 5.5% and 94.5% confidence interval, yes, it is positively associated w/ the log(lang.per.cap). 

# (b) Now evaluate the hypothesis that language diversity is negatively associated with the standard deviation of length of growing season, sd.growing.season. This hypothesis follows from uncertainty in harvest favoring social insurance through larger social networks and therefore fewer languages. Again, consider log(area) as a covariate (not an interaction). Interpret your results. 

head(d)

m7H4.b <- map(
  alist(
    log.lang.per.cap ~ dnorm(mu, sigma),
    mu <- a + bg*sd.growing.season + ba*log.area,
    a ~ dnorm(0, 10),
    bg ~ dnorm(0, 1),
    ba ~ dnorm(0, 1),
    sigma ~ dunif(0, 10)
  ), data = d)
  
precis(m7H4.b)

# plot bivariate posteriors, counterfactual plots
min(d$sd.growing.season); max(d$sd.growing.season)
sd.growing.season.seq <- seq(-1, 7, by = 0.25)
log.area.avg <- mean(d$log.area)
pred.data <- data.frame(
  sd.growing.season = sd.growing.season.seq,
  log.area = log.area.avg
)

# compute counterfactual data
mu <- link(m7H4.b, data = pred.data)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI)

d.A1 <- dd_noSey[dd_noSey$cont_africa==1,]

# plot 
plot(log.lang.per.cap ~ sd.growing.season, data=d, col=rangi2)
lines(sd.growing.season.seq, mu.mean, col=rangi2)
shade(mu.PI, sd.growing.season.seq, col = col.alpha(rangi2, 0.3))

# based on the plot, sd.growing.season is negatively correlated log.lang.per.cap. However, the confidence decreases as the stdv of growing season increases. 

# (c) Finally, evaluate the hypothesis that mean.growing.season and sd.growing.season interact to synergistically reduce language diversity. The idea is that, in nations with longer average growing seasons, high variance makes storage and redistribution even more important than it would be otherwise. That way, people can cooperate to preserve and protect windfalls to be used during the droughts. These forces in turn may lead to greater social integration and fewer languages. 

head(d)

m7H4.c <- map(
  alist(
    log.lang.per.cap ~ dnorm(mu, sigma),
    mu <- a + bgs*sd.growing.season + bgm*mean.growing.season + bgms*sd.growing.season*mean.growing.season + ba*log.area,
    a ~ dnorm(0, 10),
    bgs ~ dnorm(0, 1),
    bgm ~ dnorm(0, 1),
    bgms ~ dnorm(0, 1), 
    ba ~ dnorm(0, 1),
    sigma ~ dunif(0, 10)
  ), data = d)
  
precis(m7H4.c)
# not really? Because bgms is a negative number... 

```


















